# HLint configuration file
# https://github.com/ndmitchell/hlint
##########################

- arguments:
    - --color
    - --cpp-simple
    - -XQuasiQuotes

- modules:
    - { name: [Data.Set, Data.HashSet], as: Set }
    - { name: [Data.Map, Data.Map.Strict], as: Map }

- error: { lhs: drop 1, rhs: tail }

- warn: { name: Use explicit module export list }

- group: { name: future, enabled: true }
- group: { name: monomorphic, enabled: true }
- group: { name: codeworld, enabled: true }
- group: { name: teaching, enabled: true }
