name:                AdventOfCode2020
version:             2.0.2.0
github:              "bionikspoon/HaskellAdventOfCode2020"
license:             MIT
author:              "Manu Phatak"
maintainer:          "bionikspoon@gmail.com"
copyright:           "2020 Manu Phatak"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/bionikspoon/HaskellAdventOfCode2020#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- containers

library:
  source-dirs: src

tests:
  AdventOfCode2020-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AdventOfCode2020
    - hspec-discover
    - hspec

build-tools:
 - implicit-hie
 - hpc-lcov
